#!/bin/bash

./mac-linux-build-deps;

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        echo "OS => linux-gnu";
        cd .. && Scripts/premake5-linux gmake2 premake5.lua;
elif [[ "$OSTYPE" == "darwin"* ]]; then
        echo "OS => darwin";
        cd .. && Scripts/premake5-mac gmake2 premake5.lua;
else
        echo "OS => $OSTYPE, premake for OS NOT supported in script";
fi

make;
