#!/bin/bash

Scripts/mac-linux-build-deps;

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        echo "OS => linux-gnu";
        Scripts/Premake/premake5-linux gmake2 --file=premake5.lua;
elif [[ "$OSTYPE" == "darwin"* ]]; then
        echo "OS => darwin";
        Scripts/Premake/premake5-mac gmake2 --file=premake5.lua;
else
        echo "OS => $OSTYPE, premake for OS NOT supported in script";
fi

make;
