#!/bin/sh

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        echo "OS => linux-gnu";
        cd .. && Scripts/premake5-linux gmake2 build_dependencies.lua;
elif [[ "$OSTYPE" == "darwin"* ]]; then
        echo "OS => darwin";
        cd .. && Scripts/premake5-mac gmake2 build_dependencies.lua;
else
        echo "OS => $OSTYPE, premake for OS NOT supported in script";
fi

cp -f R-core/vendor/submodulePremakes/premake5_glfw.lua R-core/vendor/glfw/premake5.lua;
cp -f R-core/vendor/submodulePremakes/premake5_imgui.lua R-core/vendor/glfw/premake5.lua;

cd R-core/vendor/imgui && make;
cd ../glfw && make;
cd ../glad && make;
